import { portableIntegration, portableCatalog } from "./portable";
import { discoverRecipes } from "./discovery";
import { z } from "zod";
import { RESOURCES } from "../core/resources";
import { SEENE_BRAND } from "../core/branding";
import { ProjectResultSchema, ProjectStateSchema, type ProjectResult, type ProjectState } from "../core/project";
import * as services from "./services";
import { fault } from "./errors";
import { generatedPreview, htmlEntry, inspectConfig, inspectEntry } from "./vite";

const PackageSchema = z.object({
  name: z.string().optional(), version: z.string().optional(), packageManager: z.string().optional(),
  workspaces: z.unknown().optional(),
  dependencies: z.record(z.string(), z.string()).optional(),
  devDependencies: z.record(z.string(), z.string()).optional(),
  scripts: z.record(z.string(), z.string()).optional(),
  exports: z.unknown().optional(),
});
const PendingSchema = z.strictObject({ project: ProjectStateSchema, original: z.string() });
type PackageManager = "npm" | "pnpm" | "yarn" | "bun";
const statePath = ".seene/project.json";
const pendingPath = ".seene/pending.json";

const SEENE_PACKAGE = "@thatg33k/seene";
// Generated instructions must use the consumer's own package manager, not assume pnpm.
const execPrefix = (manager: PackageManager) =>
  manager === "npm" ? "npx" : manager === "pnpm" ? "pnpm exec" : manager === "yarn" ? "yarn" : "bunx";
function legacyAgentHandoff(manager: PackageManager) {
  const run = `${execPrefix(manager)} seene`;
  return `# ${SEENE_BRAND.title}

${SEENE_BRAND.url}

Generated by Seene init. Authoring guide format: ${RESOURCES["authoring-guide"]().version}.

From this project root, run \`${run} guide --json\` and read the returned workflow and capabilities.api before authoring. That command reads this installed version's canonical guide; it owns the scene instructions and examples.

Use the installed \`${SEENE_PACKAGE}\` and \`${SEENE_PACKAGE}/preview\` exports and their TypeScript declarations for the exact API. This app's recipe directory is \`src/seene/scenes\`; read capabilities.api.recipes in the guide for its file contract. In a Vite host, add \`seeneCreateScenePlugin()\` from \`${SEENE_PACKAGE}/vite\` to the existing plugins array so Studio can create recipe/source pairs through the host dev server.

Tell your coding agent the desired host page route or component path, together with this file. Run \`${run} scenes --json\` to inspect the app's catalog and \`${run} open --url <running-app-origin>\` to open its existing dev server.
`;
}
function agentHandoff(manager: PackageManager = "pnpm", adapter?: ProjectState["adapter"]) {
  const guide = RESOURCES["authoring-guide"]();
  const run = `${execPrefix(manager)} seene`;
  const handoff = {
    path: "SEENE.md" as const,
    guideCommand: `${run} guide --json`,
    guideVersion: guide.version,
    prompt: "Open the Seene studio, select your app components, and use the camera inspector to compose cinematic perspective, focal depth and motion.",
  };
  const connection = adapter === "next-app" || adapter === "next-pages"
    ? `Next.js connection: init generated a development-only Studio route at \`/seene\` and a local scene-creation API at \`/api/seene/create-scene\`; it does not rewrite your homepage or layouts. Keep \`next dev\` running and open it with \`${run} open --url http://localhost:3000\`. The route inherits the host layout and providers.`
    : adapter === "react"
      ? `Manual React connection: init generated \`src/seene/ProjectPreview.jsx\` and \`src/seene/catalog.js\`, but deliberately did not edit your renderer entry. Import \`SeeneProjectPreview\` from the generated file using a path relative to the entry/layout where you mount it, then wrap the existing app inside its providers with \`enabled={developmentFlag}\` (for Next.js, \`process.env.NODE_ENV === "development"\`; for Vite, \`import.meta.env.DEV\`). Leave \`active\` unset so \`?seene-preview=1\` activates it. Then start the app with its own dev script and run \`${run} open --url <origin>\`. Until mounted, \`open\` reports \`manual-preview\` rather than claiming the route is ready.`
      : `Vite connection: init wraps the existing React root and generated \`src/seene/ProjectPreview.tsx\`; open the running app with \`${run} open --url http://localhost:5173\`. To let Studio create recipe/component files on the Vite dev server, add \`seeneCreateScenePlugin()\` from \`${SEENE_PACKAGE}/vite\` to the existing plugins array without removing the React plugin.`;
  const sync = adapter === "next-app" || adapter === "next-pages" || adapter === "react"
    ? `For Next.js and manual React connections, run \`${run} sync\` after adding or removing scene/component pairs; this refreshes the generated static import catalog.`
    : "The Vite glob discovers recipe/component pairs directly; its development server refreshes the catalog when those files change.";
  const text = `# ${SEENE_BRAND.title}

${SEENE_BRAND.url}

Generated by Seene init. Authoring guide format: ${handoff.guideVersion}.

## First steps

From this project root, run \`${run} guide --json\` for the canonical API, recipe schema, and authoring workflow for this installed version. Import runtime primitives from \`${SEENE_PACKAGE}\` and preview components from \`${SEENE_PACKAGE}/preview\`; use their installed TypeScript declarations for exact props.

${connection}

## Scenes

Author one \`src/seene/scenes/<id>.scene.json\` recipe and one matching \`<id>.tsx\` or \`<id>.jsx\` default-exported React component. Keep these files directly in the scenes directory; IDs are lowercase slugs and must match both filenames. The component returns real UI inside matching \`Surface\` nodes; it must not render another \`ScenePreview\`.

Run \`${run} scenes --json\` to inspect validated scenes, \`${run} validate\` to verify the connection, and \`${run} open --url <running-app-origin>\` to open the existing dev server. ${sync}
`;
  return { handoff, text };
}
const configs = ["vite.config.ts", "vite.config.js", "vite.config.mts", "vite.config.mjs", "vite.config.cts", "vite.config.cjs"];
const locks = ["package-lock.json", "npm-shrinkwrap.json", "yarn.lock", "pnpm-lock.yaml", "bun.lock", "bun.lockb"];
function decode<T>(text: string, schema: z.ZodType<T>, target: string): T {
  try { return schema.parse(JSON.parse(text)); }
  catch { throw fault("invalid-file", "Invalid or conflicting project metadata; review " + target + ".", target); }
}
async function packageAt(root: string, target: string) {
  const dependency=/^node_modules\/(react|react-dom|@thatg33k\/seene)\/package.json$/.exec(target);
  const source = dependency ? await services.readDependency(root,dependency[1]) : await services.readText(root, target);
  return source === undefined ? undefined : decode(source, PackageSchema, target);
}
const packageManagers = new Set<PackageManager>(["npm", "pnpm", "yarn", "bun"]);
function managerName(value: string | undefined): PackageManager | undefined {
  const name = value?.split("@")[0].split("/")[0];
  return packageManagers.has(name as PackageManager) ? name as PackageManager : undefined;
}
function lockfileManager(target: string): PackageManager {
  if (target === "pnpm-lock.yaml") return "pnpm";
  if (target === "yarn.lock") return "yarn";
  if (target === "bun.lock" || target === "bun.lockb") return "bun";
  return "npm";
}
export async function detectPackageManager(root: string, pkg?: z.output<typeof PackageSchema>): Promise<PackageManager> {
  const declared = managerName(pkg?.packageManager);
  if (pkg?.packageManager && !declared)
    throw fault("unsupported-project", "Use npm, pnpm, Yarn, or Bun as the project package manager.");
  const existingLocks: { target: string; manager: PackageManager }[] = [];
  for (const target of locks) {
    if (await services.readText(root, target) !== undefined) {
      existingLocks.push({ target, manager: lockfileManager(target) });
    }
  }
  const lockManagers = Array.from(new Set(existingLocks.map(l => l.manager)));
  const active = managerName(services.packageManagerUserAgent());
  if (declared) {
    if (lockManagers.length === 0 || lockManagers.includes(declared)) return declared;
    throw fault("unsupported-project", "The packageManager field and lockfile identify different package managers.");
  }
  if (lockManagers.length === 0) return active ?? "npm";
  if (lockManagers.length === 1) return lockManagers[0];
  if (active && lockManagers.includes(active)) return active;
  if (lockManagers.includes("pnpm")) return "pnpm";
  const lockfileList = existingLocks.map(l => l.target).join(", ");
  throw fault("unsupported-project", `Conflicting package-manager lockfiles found: ${lockfileList}. Remove stale lockfiles or specify packageManager in package.json before setup.`);
}
async function inspectProject(root: string) {
  for (const target of [statePath, pendingPath, "package.json", ...locks, ...configs])
    await services.scopedPath(root, target);
  const pkg = await packageAt(root, "package.json");
  if (!pkg) throw fault("unsupported-project", "Choose an existing Vite React project containing package.json.");
  const packageManager = await detectPackageManager(root, pkg);
  const dependencies = { ...pkg.devDependencies, ...pkg.dependencies };
  if (!dependencies.vite || !dependencies.react
    || !dependencies["react-dom"]
    || !/^vite(?:\s+--host(?:[ =](?:localhost|127\.0\.0\.1|\[::1\]))?)?(?:\s+--port[ =]\d+)?(?:\s+--strictPort)?$/.test(pkg.scripts?.dev ?? ""))
    throw fault("unsupported-project", "Vite entry setup requires a standard Vite dev script. Use seene init --adapter react for a custom renderer without changing its build tool.");
  const found: string[] = [];
  for (const target of configs) {
    const source = await services.readText(root, target);
    if (source !== undefined) { found.push(target); inspectConfig(source, target); }
  }
  if (found.length > 1) throw fault("unsupported-project", "Multiple Vite configuration files are ambiguous.");
  if (!found.length) throw fault("unsupported-project", "Use a static Vite configuration with a standard React plugin for scene refresh.");
  const html = await services.readText(root, "index.html");
  if (html === undefined) throw fault("unsupported-project", "Expected index.html at the project root.");
  const entry = services.relativeTarget(htmlEntry(html));
  const source = await services.readText(root, entry);
  if (source === undefined) throw fault("unsupported-project", "The index.html module entry is missing.", entry);
  return { entry, source, pkg, packageManager };
}
async function hostDependenciesValid(root: string) {
  for (const name of ["react", "react-dom"]) {
    const installed = await packageAt(root, "node_modules/" + name + "/package.json");
    if (!installed?.version || !/^(?:18\.(?:[2-9]|[1-9]\d+)\.\d+|19\.\d+\.\d+)$/.test(installed.version))
      throw fault("missing-installation", `Missing or incompatible installed ${name}. Install this project's declared React 18.2+ or 19.x dependencies with its package manager, then retry seene init.`, "node_modules/" + name + "/package.json");
  }
}
async function installationValid(root: string, requireToolkit = true, requireNextRouteHandler = false) {
  const pkg = await packageAt(root, "package.json");
  await hostDependenciesValid(root);
  const toolkit = await packageAt(root, "node_modules/@thatg33k/seene/package.json");
  if (!toolkit) {
    if (requireToolkit) throw fault("missing-installation", `Seene is not installed in this project. Run seene init to install and connect ${SEENE_PACKAGE}, or add it as a dependency first.`);
    return false;
  }
  if (toolkit.name !== "@thatg33k/seene" || !(pkg?.dependencies?.["@thatg33k/seene"] || pkg?.devDependencies?.["@thatg33k/seene"]))
    throw fault("conflict", "Seene installation must match a declared @thatg33k/seene dependency.");
  const exports = toolkit.exports && typeof toolkit.exports === "object" && !Array.isArray(toolkit.exports)
    ? toolkit.exports as Record<string, unknown> : {};
  for (const subpath of ["./preview", ...(requireNextRouteHandler ? ["./next"] : [])]) {
    const entry = exports[subpath];
    const target = typeof entry === "string" ? entry
      : entry && typeof entry === "object" && !Array.isArray(entry) ? (entry as Record<string, unknown>).import : undefined;
    if (typeof target !== "string" || !target.startsWith("./")
      || await services.readDependency(root, "@thatg33k/seene", target.slice(2)) === undefined)
      throw fault("missing-installation", `Installed @thatg33k/seene lacks the ${subpath} runtime entry. Install the supported Seene package and retry.`);
  }
  return true;
}
// `npx @thatg33k/seene init` has no local tarball to install, so fall back to this exact
// published version from the registry. --package still wins for local builds and offline use.
async function sourceForInstall(root: string, source: string | undefined, version?: string) {
  if (!source) {
    if (!version)
      throw fault("package-unavailable", `Install ${SEENE_PACKAGE} in this project with its package manager, then re-run seene init.`);
    return `${SEENE_PACKAGE}@${version}`;
  }
  if (!source.endsWith(".tgz") || source.startsWith("-") || source.includes("://"))
    throw fault("invalid-input", "Package source must be an explicit local .tgz file.");
  return services.localPackageSource(root, source);
}
async function stateFor(root: string) {
  const text = await services.readText(root, statePath);
  return { text, project: text === undefined ? undefined : decode(text, ProjectStateSchema, statePath) };
}
async function previewAdapterFor(root: string, entry: string) {
  const adapter = generatedPreview(entry);
  for (const extension of ["mjs", "js", "mts", "ts", "jsx", "tsx", "json"]) {
    const candidate = adapter.path.replace(/\.[jt]sx$/, "." + extension);
    if (candidate !== adapter.path && await services.readText(root, candidate) !== undefined)
      throw fault("conflict", "A file conflicts with Seene's preview adapter import. Move or rename it before setup.", candidate);
  }
  const existing = await services.readText(root, adapter.path);
  if (existing !== undefined && existing !== adapter.text && existing !== adapter.text.replace("scene.json,tsx,jsx", "scene.json,tsx"))
    throw fault("conflict", "Seene preview adapter already contains different content. Move or rename it, then retry seene init.", adapter.path);
  return { ...adapter, existing };
}
async function initialize(root: string, packageSource: string | undefined, requestedAdapter?: string, version?: string): Promise<ProjectResult> {
  const portable = await portableHost(root, requestedAdapter);
  if (portable) return initializePortable(root, portable, packageSource, version);
  const host = await inspectProject(root);
  const adapter = await previewAdapterFor(root, host.entry);
  const adapterText = adapter.existing;
  const generated = agentHandoff(host.packageManager);
  const handoffText = await services.readText(root, generated.handoff.path);
  if (handoffText !== undefined && handoffText !== generated.text && handoffText !== legacyAgentHandoff(host.packageManager))
    throw fault("conflict", "SEENE.md already contains different content. Move or rename it to preserve your document, then retry seene init.", generated.handoff.path);
  const saved = await stateFor(root);
  const pendingText = await services.readText(root, pendingPath);
  const pending = pendingText === undefined ? undefined : decode(pendingText, PendingSchema, pendingPath);
  if (saved.project) checkState(saved.project, host.entry);
  if (pending) {
    checkState(pending.project, host.entry);
    if (saved.project && saved.project.projectId !== pending.project.projectId)
      throw fault("conflict", "Pending setup belongs to another project identity.", pendingPath);
  }
  const project = saved.project ?? pending?.project ?? ProjectStateSchema.parse({
    version: 1, projectId: services.newProjectId(), entry: host.entry, packageManager: host.packageManager,
  });
  const adapted = inspectEntry(host.source, host.entry, project.projectId);
  if (pending) {
    const planned = inspectEntry(pending.original, host.entry, project.projectId);
    if ((planned.alreadyIntegrated && !saved.project) || (host.source !== pending.original && adapted.text !== planned.text))
      throw fault("conflict", "Entry changed during interrupted setup; restore the pending original or complete integration before retrying.", host.entry);
  } else if (saved.project && !adapted.integrated) {
    throw fault("conflict", "Recorded project no longer contains its Seene integration; review entry changes.", host.entry);
  }
  let installed = false;
  await hostDependenciesValid(root);
  try { installed = await installationValid(root, false); }
  catch (error) {
    if (!packageSource || !(error instanceof Error) || !("code" in error)
      || !["missing-installation", ...(pending ? ["conflict", "invalid-file"] : [])].includes(String(error.code))) throw error;
  }
  const installSource = installed ? undefined : await sourceForInstall(root, packageSource, version);
  if (saved.project && adapted.integrated && adapted.text === host.source && !pending && installed
    && handoffText === generated.text && adapterText === adapter.text)
    return { success: true, data: { project, changed: false, handoff: generated.handoff, integration: integrationInfo(project, host.entry) } };
  const journal = pendingText ?? JSON.stringify({ project, original: host.source }, null, 2) + "\n";
  if (!pendingText) await services.atomicWrite(root, pendingPath, journal, undefined);
  if (installSource) {
    await services.installPackage(root, installSource, project.packageManager);
    await installationValid(root);
  }
  const after = await inspectProject(root);
  if (after.entry !== host.entry || after.source !== host.source)
    throw fault("conflict", "Project entry changed during installation; retry after reviewing it.", host.entry);
  if ((await previewAdapterFor(root, host.entry)).existing !== adapterText)
    throw fault("conflict", "Seene preview adapter changed during setup; review it before retrying.", adapter.path);
  if (handoffText === undefined) await services.atomicWrite(root, generated.handoff.path, generated.text, undefined);
  else if (handoffText !== generated.text) await services.atomicWrite(root, generated.handoff.path, generated.text, handoffText);
  else if (await services.readText(root, generated.handoff.path) !== generated.text)
    throw fault("conflict", "SEENE.md changed during setup; review it before retrying seene init.", generated.handoff.path);
  if (adapterText !== adapter.text) await services.atomicWrite(root, adapter.path, adapter.text, adapterText);
  if (adapted.text !== host.source) await services.atomicWrite(root, host.entry, adapted.text, host.source);
  const state = JSON.stringify(project, null, 2) + "\n";
  if (!saved.project) await services.atomicWrite(root, statePath, state, saved.text);
  await services.removeText(root, pendingPath, journal);
  return { success: true, data: { project, changed: true, handoff: generated.handoff, integration: integrationInfo(project, host.entry) } };
}
function checkState(project: ProjectState, entry: string) {
  services.relativeTarget(project.entry);
  if (project.entry !== entry) throw fault("conflict", "Recorded Seene entry differs from index.html; review the integration.", statePath);
}
async function load(root: string) {
  const portable = await stateFor(root);
  if (portable.project?.adapter) { await verifyPortable(root, portable.project); return portable.project; }
  const host = await inspectProject(root);
  const saved = await stateFor(root);
  if (!saved.project) throw fault("not-initialized", "Run seene init in this project first.");
  checkState(saved.project, host.entry);
  if (await services.readText(root, pendingPath) !== undefined)
    throw fault("incomplete-setup", "Setup was interrupted. Run seene init again to resume safely.");
  const adapted = inspectEntry(host.source, host.entry, saved.project.projectId);
  if (!adapted.alreadyIntegrated) {
    if (host.source.includes("ProjectPreview"))
      throw fault("incomplete-setup", "Run seene init to upgrade the installed preview refresh boundary.", host.entry);
    throw fault("conflict", "The recorded Seene integration is missing.", host.entry);
  }
  if (adapted.text !== host.source)
    throw fault("incomplete-setup", "Run seene init to upgrade the installed preview refresh boundary.", host.entry);
  const adapter = await previewAdapterFor(root, host.entry);
  if (adapter.existing !== adapter.text) {
    if (adapter.existing?.includes("ProjectPreview") || adapter.existing?.includes("catalog"))
      throw fault("incomplete-setup", "Run seene init to upgrade the installed preview refresh boundary.", adapter.path);
    throw fault("conflict", "The generated preview adapter is missing or changed. Review it and run seene init.", adapter.path);
  }
  await installationValid(root,true,saved.project.adapter==="next-app"||saved.project.adapter==="next-pages");
  return saved.project;
}
async function openPreview(root: string, input: z.output<typeof RESOURCES["open-preview"]>) {
  const project = await load(root);
  if (project.adapter) {
    if (project.adapter === "react") throw fault("manual-preview", "Seene generated src/seene/ProjectPreview.jsx but does not mount it in a custom React renderer. Import SeeneProjectPreview from that generated file using a path relative to your entry/layout, wrap the existing UI inside its providers with enabled={developmentFlag} (Next.js: process.env.NODE_ENV === 'development'; Vite: import.meta.env.DEV), leave active unset, then open the mounted route with ?seene-preview=1. See SEENE.md for the exact workflow.");
    const url = new URL("/seene?seene-preview=1", input.url).href;
    let html: string;
    try { html = await services.fetchText(url, 30_000); }
    catch {
      throw fault("missing-dev-server", `Could not reach or verify the Next.js Seene route at ${url}. Start this project's existing Next.js dev script and confirm the generated /seene route is present, then retry.`);
    }
    if (!html.includes('name="seene-project"') || !html.includes(project.projectId))
      throw fault("wrong-dev-server", "This URL does not serve this project's development Seene route. Start the existing app and check its origin.");
    if (input.launch) await services.openBrowser(root, url);
    return {success:true as const,data:{project,url}};
  }
  let matched = false;
  for (let attempt = 0; attempt < 5; attempt++) {
    try {
      const html = await services.fetchText(input.url);
      const entry = services.relativeTarget(htmlEntry(html, true));
      if (entry !== project.entry) throw fault("wrong-dev-server", "The dev server belongs to another entry.");
      const transformed = await services.fetchText(new URL("/" + entry, input.url).href);
      if (!transformed.includes(project.projectId) || !transformed.includes("ProjectPreview")
        || !(transformed.includes("@thatg33k_seene_preview") || transformed.includes("@thatg33k/seene/preview") || transformed.includes("/src/seene/ProjectPreview.") || transformed.includes("/src/seene/ProjectPreview.")))
        throw fault("wrong-dev-server", "Dev server does not contain this project's preview identity.");
      matched = true;
      break;
    } catch {
      if (attempt < 4) await services.pause(150);
    }
  }
  if (!matched) throw fault("missing-dev-server", "No matching Vite dev server at " + input.url + ". Start this project's existing development server, then retry with its loopback URL.");
  const url = new URL("/?seene-preview=1", input.url).href;
  if (input.launch) await services.openBrowser(root, url);
  return { success: true as const, data: { project, url } };
}
export async function executeProjectCommand(operation: unknown, input: unknown, context: { root: string; version?: string }): Promise<ProjectResult> {
  try {
    if (typeof operation !== "string" || !Object.hasOwn(RESOURCES, operation))
      throw fault("invalid-operation", "Unknown project operation.");
    const schema = RESOURCES[operation as keyof typeof RESOURCES];
    if (!("safeParse" in schema)) throw fault("invalid-operation", "This operation is not a project command.");
    const parsed = schema.safeParse(input);
    if (!parsed.success) return ProjectResultSchema.parse({ success: false, issues: parsed.error.issues.map(issue => ({
      code: "invalid-input", message: issue.message, path: issue.path.join("."),
    })) });
    if (!context || typeof context.root !== "string") throw fault("invalid-scope", "Provide an absolute local project root.");
    const root = await services.canonicalRoot(context.root);
    let result: ProjectResult;
    if (operation === "init-project") result = await initialize(root, (parsed.data as z.output<typeof RESOURCES["init-project"]>).packageSource, (parsed.data as z.output<typeof RESOURCES["init-project"]>).adapter, context.version);
    else if (operation === "sync-project") result = await synchronize(root);
    else if (operation === "open-preview") result = await openPreview(root, parsed.data as z.output<typeof RESOURCES["open-preview"]>);
    else result = { success: true, data: { project: await load(root) } };
    return ProjectResultSchema.parse(result);
  } catch (error) {
    const known = error instanceof Error && "code" in error && "target" in error;
    return { success: false, issues: [{
      code: known ? String(error.code) : "project-error",
      message: known ? error.message : "Unable to access the project. Check local files and permissions, then retry.",
      ...(known && typeof error.target === "string" ? { path: error.target } : {}),
    }] };
  }
}
const ManagedSchema = z.strictObject({project:ProjectStateSchema,files:z.record(z.string(),z.string())});
const managedPath = ".seene/integration.json";
const portablePendingPath = ".seene/integration-pending.json";
type PortableHost = {adapter:"react"|"next-app"|"next-pages";entry:string};
async function ensureNextRouteAvailable(root:string, directory:string, basename:string) {
  for (const extension of ["js", "jsx", "ts", "tsx", "md", "mdx"]) {
    const target=directory+"/"+basename+"."+extension;
    if(await services.readText(root,target)!==undefined)
      throw fault("conflict","A host route already occupies Seene's route. Move or rename it before setup.",target);
  }
}
async function nextAppRouteDirectory(root:string, base:string):Promise<string|undefined> {
  for(const extension of ["tsx","jsx","js"])
    if(await services.isRegularFile(root,base+"/layout."+extension))return base;
  const files=await services.scanDirectory(root,base,2048);
  const layouts=files.filter(file=>/\/layout\.(?:tsx|jsx|js)$/.test(file));
  const routeGroups=layouts.filter(file=>{
    const relative=file.slice(base.length+1).replace(/\/layout\.(?:tsx|jsx|js)$/,"" );
    return relative.split("/").every(segment=>segment.length>2&&segment.startsWith("(")&&segment.endsWith(")"));
  }).map(file=>file.replace(/\/layout\.(?:tsx|jsx|js)$/,""));
  for(const directory of routeGroups) {
    for(const extension of ["tsx","jsx","js"])
      if(await services.isRegularFile(root,directory+"/page."+extension))return directory;
  }
  return routeGroups[0];
}
async function portableHost(root:string, requested?:string):Promise<PortableHost|undefined> {
  const pkg = await packageAt(root,"package.json");
  if (!pkg) throw fault("unsupported-project","Run seene init in your existing React application's package directory.");
  const deps = {...pkg.devDependencies,...pkg.dependencies};
  if (!deps.react || !deps["react-dom"]) throw fault("unsupported-project","This package needs a React DOM renderer.");
  await detectPackageManager(root, pkg);
  const saved = await stateFor(root);
  if (saved.project?.adapter) return {adapter:saved.project.adapter,entry:saved.project.entry};
  if (requested === "react") return {adapter:"react",entry:"src/seene/ProjectPreview.jsx"};
  const nextDevScript = /(?:^|\s|&&\s*|;\s*)next\s+dev(?:\s|$)/.test(pkg.scripts?.dev ?? "");
  if (deps.next || nextDevScript) {
    if (!deps.next)
      throw fault("unsupported-project", "A Next.js dev script was detected, but package.json does not declare next. Add Next.js as a project dependency; Seene will not route this app through Vite setup.");
    for (const base of ["app","src/app"]) {
      const routeDirectory=await nextAppRouteDirectory(root,base);
      if(routeDirectory) {
        await ensureNextRouteAvailable(root,routeDirectory+"/seene","page");
        await ensureNextRouteAvailable(root,routeDirectory+"/api/seene/create-scene","route");
        return {adapter:"next-app",entry:routeDirectory+"/seene/page.jsx"};
      }
    }
    for (const base of ["pages","src/pages"]) {
      if ((await services.scanDirectory(root,base,1024)).length) {
        await ensureNextRouteAvailable(root,base,"seene");
        await ensureNextRouteAvailable(root,base+"/api/seene","create-scene");
        return {adapter:"next-pages",entry:base+"/seene.jsx"};
      }
    }
    return {adapter:"react",entry:"src/seene/ProjectPreview.jsx"};
  }
  if (deps.vite) {
    if (!saved.project && await services.readText(root,pendingPath) === undefined) {
      try {
        const host=await inspectProject(root);
        inspectEntry(host.source,host.entry,"00000000-0000-4000-8000-000000000000");
      } catch(error) {
        if (!(error instanceof Error) || !("code" in error) || error.code!=="unsupported-project") throw error;
        return {adapter:"react",entry:"src/seene/ProjectPreview.jsx"};
      }
    }
    return undefined;
  }
  return {adapter:"react",entry:"src/seene/ProjectPreview.jsx"};
}
function integrationInfo(project:ProjectState, entry?: string) {
  if (!project.adapter && entry) {
    return {
      kind: "react",
      component: entry,
      instructions: "Vite setup wraps the existing React root. Keep its dev server running; seene open verifies the Vite entry before opening the preview.",
    };
  }
  return {
    kind:project.adapter!,component:"src/seene/ProjectPreview.jsx",
    ...(project.adapter === "next-app" || project.adapter === "next-pages" ? {route:"/seene"} : {}),
    instructions:project.adapter === "react"
      ? "Manual integration required: mount SeeneProjectPreview from src/seene/ProjectPreview.jsx around your existing UI with a development-only enabled prop; open only after mounting. See SEENE.md."
      : "Seene generated a development-only /seene Studio route; it does not rewrite the existing Next.js homepage.",
  };
}
async function catalogSource(root:string) {
  const catalog = await discoverRecipes(root);
  if (catalog.issues.length) throw fault("invalid-scenes",catalog.issues.map(issue=>issue.path+": "+issue.message).join("\n"));
  return portableCatalog(catalog.scenes);
}
async function portableFiles(root:string, project:ProjectState, catalog:string) {
  const entry=project.entry.startsWith("src/")?project.entry.slice(4):project.entry;
  const segments=entry.split("/");
  const validNextAppEntry=segments[0]==="app"&&segments.at(-2)==="seene"&&segments.at(-1)==="page.jsx"
    &&segments.slice(1,-2).every(segment=>segment.length>2&&segment.startsWith("(")&&segment.endsWith(")"));
  const allowed=project.adapter==="next-app" ? validNextAppEntry
    : project.adapter==="next-pages" ? ["pages/seene.jsx","src/pages/seene.jsx"].includes(project.entry)
      : project.entry==="src/seene/ProjectPreview.jsx";
  if(!allowed)throw fault("conflict","Recorded entry is not a valid host connection.");
  const files = portableIntegration(project,catalog);
  return files;
}
async function initializePortable(root:string, host:PortableHost, packageSource?:string, version?:string):Promise<ProjectResult> {
  const saved=await stateFor(root);
  const pendingText=await services.readText(root,portablePendingPath);
  const pending=pendingText===undefined?undefined:decode(pendingText,ManagedSchema,portablePendingPath);
  const existingText=await services.readText(root,managedPath);
  const existing=existingText===undefined?undefined:decode(existingText,ManagedSchema,managedPath);
  const pkg = await packageAt(root, "package.json");
  const manager = await detectPackageManager(root, pkg);
  const project=saved.project??pending?.project??ProjectStateSchema.parse({version:1,projectId:services.newProjectId(),entry:host.entry,packageManager:manager,adapter:host.adapter});
  if(project.adapter!==host.adapter||project.entry!==host.entry)throw fault("conflict","Existing Seene setup uses another host connection.");
  for(const record of [pending,existing])if(record && JSON.stringify(record.project)!==JSON.stringify(project))throw fault("conflict","Seene setup identity changed.");
  const catalog=existing?.files["src/seene/catalog.js"]??pending?.files["src/seene/catalog.js"]??await catalogSource(root);
  const files=await portableFiles(root,project,catalog);
  const generated=agentHandoff(manager,project.adapter);
  files[generated.handoff.path]=generated.text;
  if(pending && JSON.stringify(pending.files)!==JSON.stringify(files))throw fault("conflict","Pending setup differs.");
  if(existing) {
    for(const target of Object.keys(existing.files))
      if(target!=="SEENE.md" && !Object.hasOwn(files,target))throw fault("conflict","A previously managed Seene file is no longer part of this integration.",target);
  }
  for(const [target,text] of Object.entries(files)) {
    const current=await services.readText(root,target);
    const recorded=target==="SEENE.md"?existing?.files[target]:undefined;
    if(current!==undefined && current!==text && current!==recorded)throw fault("conflict","Seene will not overwrite an existing file.",target);
  }
  await hostDependenciesValid(root);
  const needsNextHandler=host.adapter==="next-app"||host.adapter==="next-pages";
  let installed=false;
  try { installed=await installationValid(root,false,needsNextHandler); }
  catch(error) {
    if((!packageSource&&!version) || !(error instanceof Error) || !("code" in error) || error.code!=="missing-installation")throw error;
  }
  const source=installed?undefined:await sourceForInstall(root,packageSource,version);
  if(existing && saved.project && !pending && existing.files["SEENE.md"]===generated.text && JSON.stringify(existing.files)===JSON.stringify(files)) {
    await verifyPortable(root,project);
    return {success:true,data:{project,changed:false,handoff:generated.handoff,integration:integrationInfo(project)}};
  }
  const journal=JSON.stringify({project,files},null,2)+"\n";
  if(!pendingText)await services.atomicWrite(root,portablePendingPath,journal,undefined);
  if(source){await services.installPackage(root,source,project.packageManager);await installationValid(root,true,needsNextHandler);}
  for(const [target,text] of Object.entries(files)) {
    const current=await services.readText(root,target);
    if(current===undefined)await services.atomicWrite(root,target,text,undefined);
    else if(current!==text) {
      const recorded=target==="SEENE.md"?existing?.files[target]:undefined;
      if(current!==recorded)throw fault("conflict","File changed during setup.",target);
      await services.atomicWrite(root,target,text,current);
    }
  }
  if(!existing)await services.atomicWrite(root,managedPath,journal,undefined);
  else if(JSON.stringify(existing.files)!==JSON.stringify(files))
    await services.atomicWrite(root,managedPath,journal,existingText);
  if(!saved.project)await services.atomicWrite(root,statePath,JSON.stringify(project,null,2)+"\n",saved.text);
  await services.removeText(root,portablePendingPath,pendingText??journal);
  return {success:true,data:{project,changed:true,handoff:generated.handoff,integration:integrationInfo(project)}};
}
async function verifyPortable(root:string,project:ProjectState) {
  if(await services.readText(root,portablePendingPath)!==undefined)throw fault("incomplete-setup","Run seene init to resume.");
  const text=await services.readText(root,managedPath);
  if(text===undefined)throw fault("incomplete-setup","Missing managed connection. Run seene init.");
  const managed=decode(text,ManagedSchema,managedPath);
  if(JSON.stringify(managed.project)!==JSON.stringify(project))throw fault("conflict","Managed project identity differs.");
  const expected=await portableFiles(root,project,managed.files["src/seene/catalog.js"]??"");
  expected["SEENE.md"]=agentHandoff(project.packageManager,project.adapter).text;
  if(JSON.stringify(expected)!==JSON.stringify(managed.files))throw fault("conflict","Managed file list differs.");
  for(const [target,content] of Object.entries(expected))if(await services.readText(root,target)!==content)throw fault("conflict","Generated connection changed.",target);
  await installationValid(root,true,project.adapter==="next-app"||project.adapter==="next-pages");
}
async function synchronize(root:string):Promise<ProjectResult> {
  const project=(await stateFor(root)).project;
  if(!project)throw fault("not-initialized","Run seene init first.");
  if(!project.adapter){await load(root);return {success:true,data:{project,changed:false}};}
  const transactionPath=".seene/catalog-pending.json";
  const interrupted=await services.readText(root,transactionPath);
  if(interrupted!==undefined) {
    const pending=decode(interrupted,z.strictObject({before:z.string(),after:z.string()}),transactionPath);
    const recordText=await services.readText(root,managedPath);
    if(recordText===undefined)throw fault("conflict","Missing catalog ownership record.");
    const record=decode(recordText,ManagedSchema,managedPath);
    const current=await services.readText(root,"src/seene/catalog.js");
    if(![pending.before,pending.after].includes(record.files["src/seene/catalog.js"]) || ![pending.before,pending.after].includes(current??""))
      throw fault("conflict","Catalog changed during interrupted sync.");
    if(current!==pending.after)await services.atomicWrite(root,"src/seene/catalog.js",pending.after,current);
    if(record.files["src/seene/catalog.js"]!==pending.after) {
      record.files["src/seene/catalog.js"]=pending.after;
      await services.atomicWrite(root,managedPath,JSON.stringify(record,null,2)+"\n",recordText);
    }
    await services.removeText(root, transactionPath, interrupted);
  }
  await verifyPortable(root,project);
  const target="src/seene/catalog.js";
  const text=await catalogSource(root);
  const savedText=(await services.readText(root,managedPath))!;
  const managed=decode(savedText,ManagedSchema,managedPath);
  const original=managed.files[target];
  if(text===original)return {success:true,data:{project,changed:false}};
  const transaction=JSON.stringify({before:original,after:text});
  await services.atomicWrite(root,transactionPath,transaction,undefined);
  await services.atomicWrite(root,target,text,original);
  managed.files[target]=text;
  await services.atomicWrite(root,managedPath,JSON.stringify(managed,null,2)+"\n",savedText);
  await services.removeText(root,transactionPath,transaction);
  return {success:true,data:{project,changed:true}};
}
